/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lzb_machinecontrol_serial_SerialConnect */

#ifndef _Included_com_lzb_machinecontrol_serial_SerialConnect
#define _Included_com_lzb_machinecontrol_serial_SerialConnect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lzb_machinecontrol_serial_SerialConnect
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_lzb_machinecontrol_serial_SerialConnect_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_lzb_machinecontrol_serial_SerialConnect
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lzb_machinecontrol_serial_SerialConnect_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
